@startuml arquitectura
package mastermind #DDDDDD { }
mastermind ..> mastermind.views
mastermind ..> mastermind.models
mastermind ..> mastermind.views.console
mastermind ..> mastermind.views.graphics

package mastermind.models #DDDDDD { }
package java.util{ }
mastermind.models .down.> java.util

package mastermind.utils #DDDDDD { }
package java.io{ }
mastermind.utils .down.> java.io

package mastermind.views #DDDDDD { }
mastermind.views .down.> mastermind.models

package mastermind.views.console #DDDDDD { }
mastermind.views.console .down.> mastermind.views
mastermind.views.console .down.> mastermind.models
mastermind.views.console .down.> mastermind.utils

package mastermind.views.graphics #DDDDDD { }
package java.awt{ }
mastermind.views.graphics .down.> java.awt
package java.awt.event{ }
mastermind.views.graphics .down.> java.awt.event
mastermind.views.graphics .down.> mastermind.views
mastermind.views.graphics .down.> mastermind.models
package javax.swing{ }
mastermind.views.graphics .down.> javax.swing

@enduml
